name: Go Cross-Platform Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

permissions:
  contents: read

jobs:
  makefile-build:
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        go-version: ['1.24', '1.25']

    steps:
      - uses: actions/checkout@v5

      - name: Configure environment to avoid toolchain installs
        shell: bash
        run: echo "GOTOOLCHAIN=local" >> "$GITHUB_ENV"
        
      - uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.go-version }}"
  
      - name: build binary from makefile
        run: make build
      
      - name: dep from makefile
        run: make dep

      - name: dep+build from makefile
        run: make
        
  go-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
        go-version: ['1.24', '1.25']
        goos: [linux, freebsd, darwin, windows]
        exclude:
          - { os: macos-latest, goos: linux }
          - { os: macos-latest, goos: freebsd }
          - { os: macos-latest, goos: windows }
          - { os: ubuntu-24.04, goos: darwin }
          - { os: ubuntu-24.04, goos: windows }
          - { os: windows-latest, goos: linux }
          - { os: windows-latest, goos: freebsd }
          - { os: windows-latest, goos: darwin }

    steps:
      - uses: actions/checkout@v5

      - name: Configure environment to avoid toolchain installs 
        shell: bash
        run: echo "GOTOOLCHAIN=local" >> "$GITHUB_ENV"

      - uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Build binary
        run: |
          if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
            set CGO_ENABLED=0
            go build -ldflags="-s -w" -o dnscollector.exe .
          else
            CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=amd64 go build -ldflags="-s -w" -o dnscollector *.go
          fi
        shell: bash

  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          docker buildx build \
            --build-arg VERSION=dev \
            --platform linux/amd64,linux/arm64,linux/i386 \
            --file Dockerfile -t dnscollector .
