name: Go Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

permissions:
  contents: read

env:
  PROM_VERSION: "3.7.3"
  GENTAP: "1.0.3"
  PYTHON_VERSION: '3.14'
  GO_VERSION: '1.25'

jobs:
  build_bin:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Build Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dnscollector *.go

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v5
        with:
          name: dnscollector
          path: dnscollector

  testunit:
    strategy:
      matrix:
        os-version: [ 'ubuntu-24.04' ]
        go-version: [ '1.24', '1.25' ]
        package:
          - '.'
          - 'pkgconfig'
          - 'pkginit'
          - 'dnsutils'
          - 'workers'
          - 'transformers'
          - 'telemetry'
    
    runs-on: "${{ matrix.os-version }}"

    steps:
    - uses: actions/checkout@v6

    - name: Configure environment to avoid toolchain installs 
      shell: bash
      run: echo "GOTOOLCHAIN=local" >> "$GITHUB_ENV"

    - uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Show Go version
      run: |
        go version

    - name: Test ${{ matrix.package }}
      run: go test -timeout 240s -exec sudo ./${{ matrix.package }}/ -race -cover -v
      
  config:
    needs: build_bin
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
  
    - name: Download Binary Artifact
      uses: actions/download-artifact@v6
      with:
        name: dnscollector

    - name: Make Binary Executable
      run: chmod +x dnscollector

    - uses: actions/setup-python@v6
      with:
        python-version: "${{ env.PYTHON_VERSION }}"

    - name: Test config
      run: |
        python3 -m unittest tests.config -v

  metrics:
    needs: build_bin
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - name: Download Binary Artifact
      uses: actions/download-artifact@v6
      with:
        name: dnscollector

    - name: Make Binary Executable
      run: chmod +x dnscollector

    - name: run collector
      run: ./dnscollector -config ./tests/testsdata/config_prom.yml &

    - name: download dnstap generator
      run: |
        wget -nv https://github.com/dmachard/dnstap-generator/releases/download/v${{ env.GENTAP }}/dnstap-generator_${{ env.GENTAP }}_linux_amd64.tar.gz
        tar xf dnstap-generator_${{ env.GENTAP }}_linux_amd64.tar.gz
        ./dnstap-generator -i 127.0.0.1 -p 6000 -n 1

    - name: check prometheus format metrics
      run: |
        wget -nv https://github.com/prometheus/prometheus/releases/download/v$PROM_VERSION/prometheus-$PROM_VERSION.linux-amd64.tar.gz
        tar xf prometheus-$PROM_VERSION.linux-amd64.tar.gz
        cd prometheus-$PROM_VERSION.linux-amd64/
        curl -u admin:changeme http://127.0.0.1:8081/metrics | ./promtool check metrics

  count:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Configure environment to avoid toolchain installs 
      shell: bash
      run: echo "GOTOOLCHAIN=local" >> "$GITHUB_ENV"

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run test from makefile
      run: |
        make tests

    - name: Count lines of code
      run: |
        make stats
